CREATE TABLE IF NOT EXISTS AnotherTest();

CREATE TABLE IF NOT EXISTS Test();

CREATE TABLE IF NOT EXISTS Root();

CREATE TABLE IF NOT EXISTS Child();

ALTER TABLE IF EXISTS AnotherTest
    ADD COLUMN IF NOT EXISTS testReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Test
    ADD COLUMN IF NOT EXISTS anotherTestReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Root
    ADD COLUMN IF NOT EXISTS parentId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Child
    ADD COLUMN IF NOT EXISTS parent NUMERIC NOT NULL REFERENCES Root;

ALTER TABLE
    AnotherTest
ADD
    FOREIGN KEY (testReference) REFERENCES Test;

ALTER TABLE
    Test
ADD
    FOREIGN KEY (anotherTestReference) REFERENCES AnotherTest;