CREATE TABLE IF NOT EXISTS AnotherTest();

CREATE TABLE IF NOT EXISTS Test();

ALTER TABLE IF EXISTS AnotherTest
    ADD COLUMN IF NOT EXISTS testReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Test
    ADD COLUMN IF NOT EXISTS anotherTestReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE
    AnotherTest
ADD
    FOREIGN KEY (testReference) REFERENCES Test;

ALTER TABLE
    Test
ADD
    FOREIGN KEY (anotherTestReference) REFERENCES AnotherTest;