CREATE TABLE IF NOT EXISTS AnotherTest();

CREATE TABLE IF NOT EXISTS Test();

CREATE TABLE IF NOT EXISTS ReferenceBoth();

ALTER TABLE IF EXISTS AnotherTest
    ADD COLUMN IF NOT EXISTS testReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Test
    ADD COLUMN IF NOT EXISTS anotherTestReference NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS ReferenceBoth
    ADD COLUMN IF NOT EXISTS anotherTest NUMERIC NOT NULL,
    ADD COLUMN IF NOT EXISTS test NUMERIC NOT NULL;

ALTER TABLE
    AnotherTest
ADD
    FOREIGN KEY (testReference) REFERENCES Test;

ALTER TABLE
    Test
ADD
    FOREIGN KEY (anotherTestReference) REFERENCES AnotherTest;

ALTER TABLE
    ReferenceBoth
ADD
    FOREIGN KEY (anotherTest) REFERENCES AnotherTest;

ALTER TABLE
    ReferenceBoth
ADD
    FOREIGN KEY (test) REFERENCES Test;