CREATE SCHEMA IF NOT EXISTS one_two_three;

CREATE SCHEMA IF NOT EXISTS this_can_be_very_nested_thing;

CREATE SCHEMA IF NOT EXISTS two;

CREATE TABLE IF NOT EXISTS Foo();

CREATE TABLE IF NOT EXISTS one_two_three.Foo();

CREATE TABLE IF NOT EXISTS this_can_be_very_nested_thing.Foo();

CREATE TABLE IF NOT EXISTS two.Foo();

ALTER TABLE IF EXISTS Foo ADD COLUMN IF NOT EXISTS myId TEXT NOT NULL;

ALTER TABLE IF EXISTS one_two_three.Foo
    ADD COLUMN IF NOT EXISTS myId TEXT NOT NULL;

ALTER TABLE IF EXISTS this_can_be_very_nested_thing.Foo
    ADD COLUMN IF NOT EXISTS myId TEXT NOT NULL;

ALTER TABLE IF EXISTS two.Foo
    ADD COLUMN IF NOT EXISTS myId TEXT NOT NULL;