CREATE TABLE IF NOT EXISTS Test();

CREATE TABLE IF NOT EXISTS AnotherTest();

ALTER TABLE IF EXISTS Test
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS AnotherTest
    ADD COLUMN IF NOT EXISTS test_id NUMERIC NOT NULL REFERENCES Test,
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;