CREATE TABLE IF NOT EXISTS AnotherTest();

CREATE TABLE IF NOT EXISTS Test();

ALTER TABLE IF EXISTS AnotherTest
    ADD COLUMN IF NOT EXISTS myId NUMERIC PRIMARY KEY;

ALTER TABLE IF EXISTS Test
    ADD COLUMN IF NOT EXISTS anotherTest NUMERIC NOT NULL REFERENCES AnotherTest;