CREATE TYPE Test AS ENUM ('10', '100');

CREATE TABLE Ten (id Test DEFAULT '10' PRIMARY KEY);

CREATE TABLE Hundred (id Test DEFAULT '100' PRIMARY KEY);

CREATE TABLE ReferencesThem (
    ten Test NOT NULL REFERENCES Ten,
    hundred Test NOT NULL DEFAULT '100' REFERENCES Hundred
);